[project]
name = "Flask-Ollama"
version = "0.1.0"
description = "Flask app for talking to local Ollama models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "ollama>=0.4.7",
    "requests>=2.32.3",
]
